### ISSUE TITLE
Home Assistant lock component request

### ISSUE THREAD

**Issue by B1tMaster** [Bahnburner/pykevoplus#1]
Hi, 
I am thinking about buying a new Kevo Lock.. Been using HA for a year now. currently on haas.io.
Was wondering if you had any plans to PR this into a component in HA, so it is natively supported?

How does this library work or you so far with HA?  Basically, is Kevo lock worth buying? If I can't control it from HA, it would be a waste for me. 

Thanks.
-D.

**Comment by Bahnburner** [comment]
There are plans in the works by @gaggle331 on the home assistant community forums to integrate this into a full hass component, but since August the work has pretty much stalled. The unofficial component has been posted and for the most part, it works as expected. Recently though, Unikey/Kwikset has implemented something on the server-side that is returning Error 500's after a few hours of use. Restarting Hass rectifies the issue, for a few hours. We're unsure of the means they're using to determine who is using the component, as using python scripts to execute commands directly through pykevoplus/pykevocontrol continues to work without issue. 

With that being said, while the Kevo locks are a neat toy, if I knew at the time of purchase what I know now, I would have bought standard z-wave locks instead. They work reliable when using them as advertised, but Unikey/Kevo definitely doesn't want the locks interacting with other devices anytime soon. They showed off a z-wave enabled Kevo Plus bridge a few years ago at CES, but it appears to be vaporware at this point, as nothing has come to fruition.
